
language: objective-c
osx_image: xcode9
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild -project Example/Pods/Pods.xcodeproj -scheme InjectionTDD -configuration Debug -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO  build  | xcpretty
