
language: objective-c
osx_image: xcode9
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- export EXPANDED_CODE_SIGN_IDENTITY=- # workaround for https://github.com/CocoaPods/CocoaPods/issues/7708
- export EXPANDED_CODE_SIGN_IDENTITY_NAME=- # workaround for https://github.com/CocoaPods/CocoaPods/issues/7708
- pod lib lint --verbose

- set -o pipefail && xcodebuild -project Example/Pods/Pods.xcodeproj -scheme InjectionTDD -configuration Debug -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO  build  | xcpretty
- cd Example/build/Debug-iphonesimulator/InjectionTDD/ && zip -r ../../../../InjectionTDD.framework.zip InjectionTDD.framework/ && cd -
- cd scripts/update_breakpoints/ && zip -r ../../update_breakpoints.zip * && cd -

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: 
    - "InjectionTDD.framework.zip"
    - "update_breakpoints.zip"
  skip_cleanup: true
  on:
    tags: true