
language: objective-c
osx_image: xcode8.3
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild -project Example/Pods/Pods.xcodeproj -scheme InjectionTDD -configuration Debug -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO  build  | xcpretty
- cd Example/build/Debug-iphonesimulator/InjectionTDD/ && zip -r ../../../../InjectionTDD.framework.zip InjectionTDD.framework/ && cd -
- cd scripts/update_breakpoints_binary/ && zip -r ../../update_breakpoints.zip * && cd -
- cd scripts/update_breakpoints_generic/ && zip -r ../../update_breakpoints_generic.zip * && cd -
- cd scripts/update_breakpoints_source/ && zip -r ../../update_breakpoints_source.zip * && cd -

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: 
    - "InjectionTDD.framework.zip"
    - "update_breakpoints.zip"
    - "update_breakpoints_source.zip"
    - "update_breakpoints_generic.zip"
  skip_cleanup: true
  on:
    tags: true
